apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskapp
  namespace: taskapp
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - taskapp.3.237.103.110.nip.io
      secretName: taskapp-tls-cert
  rules:
    - host: taskapp.3.237.103.110.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taskapp-frontend # Verified matching frontend service handle
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: taskapp-backend # FIXED: Aligned perfectly with your active running backend service
                port:
                  number: 5000

