apiVersion: v1
kind: Secret
metadata:
  name: taskapp-placeholder-secret
  namespace: taskapp
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Rhc2thcHA6dGFza2FwcDEyM0Bwb3N0Z3Jlcy50YXNrYXBwLnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvdGFza2FwcA==
  SECRET_KEY: bUtMdzVzKy9SRHJqc2tMUDNKcDNZMkhyejQ3bzh0WU1udDZGdmZJb003ST0=

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: taskapp
type: Opaque
stringData:
  DATABASE_PASSWORD: "taskapp123"
  POSTGRES_PASSWORD: "taskapp123"
