apiVersion: v1
kind: Secret
metadata:
  name: taskapp-placeholder-secret
  namespace: taskapp
type: Opaque
data:
  # FIXED: Replaced fake data hashes with your active cluster infrastructure parameters
  DATABASE_URL: cG9zdGdyZXNxbDovL3Rhc2thcHA6dGFza2FwcDEyM0Bwb3N0Z3Jlcy50YXNrYXBwLnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvdGFza2FwcA==
  SECRET_KEY: bUtMdzVzKy9SRHJqc2tMUDNKcDNZMkhyejQ3bzh0WU1udDZGdmZJb003ST0=

