apiVersion: v1
kind: Secret
metadata:
  name: taskapp-placeholder-secret
  namespace: taskapp
type: Opaque
data:
  # Safe, un-encrypted placeholder tags to bypass engine compilation checks
  DATABASE_URL: ZmFrZS1kYXRhYmFzZS11cmw=
  SECRET_KEY: ZmFrZS1zZWNyZXQta2V5
