apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskapp-backend
  namespace: taskapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/ts-a-devops/taskapp-backend@sha256:7ebe1b93baef2c95098d6ce253879b4067ffbe39645a9c4fa5513aff202e4a70
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          # INJECT THESE PROBE DEFINITIONS TO TRIGGER A 200 HEALTH HANDSHAKE
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
            - name: POSTGRES_DB
              value: "taskapp"
            - name: POSTGRES_USER
              value: "taskapp"
            - name: POSTGRES_PASSWORD
              value: "taskapp123"
            - name: DATABASE_URL
              value: "postgresql://taskapp:taskapp123@postgres.taskapp.svc.cluster.local:5432/taskapp"
            - name: SECRET_KEY
              value: "mKLw5s+/RDrjskLP3Jp3Y2Hrz47n8tYMnt6FvfIoM7I="
