apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskapp-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lovesmesegun/capstone-phoenix.git # FIXED: Added correct slash separations
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc # FIXED: Set true standard internal API server endpoint
    namespace: taskapp
  # PERMANENT VISUAL FIX: Tells the engine to ignore bare-metal networking state variations
  ignoreDifferences:
  - group: networking.k8s.io
    kind: Ingress
    jsonPointers:
    - /status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
